//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a>
//         Any modifications to this file will be lost upon recompilation of the source schema.
//         Generated on: 2018.08.30 at 01:59:18 AM MSK
//


package by.htp.verishko.task1.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CATEGORY" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SUBCATEGORY" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="NEWS_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="PROVIDER_AUTHOR_AUTHORS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="DATE_OF_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="NEWS_BODY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "category"
})
@XmlRootElement(name = "CATALOG")
public class CATALOG {

    @XmlElement(name = "CATEGORY", required = true)
    protected List<CATALOG.CATEGORY> category;

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCATEGORY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CATALOG.CATEGORY }
     * 
     * 
     */
    public List<CATALOG.CATEGORY> getCATEGORY() {
        if (category == null) {
            category = new ArrayList<CATALOG.CATEGORY>();
        }
        return this.category;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SUBCATEGORY" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="NEWS_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="PROVIDER_AUTHOR_AUTHORS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="DATE_OF_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="NEWS_BODY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subcategory"
    })
    public static class CATEGORY {

        @XmlElement(name = "SUBCATEGORY", required = true)
        protected List<CATALOG.CATEGORY.SUBCATEGORY> subcategory;
        @XmlAttribute(name = "Name", required = true)
        protected String name;

        /**
         * Gets the value of the subcategory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subcategory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSUBCATEGORY().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CATALOG.CATEGORY.SUBCATEGORY }
         * 
         * 
         */
        public List<CATALOG.CATEGORY.SUBCATEGORY> getSUBCATEGORY() {
            if (subcategory == null) {
                subcategory = new ArrayList<CATALOG.CATEGORY.SUBCATEGORY>();
            }
            return this.subcategory;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="NEWS_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="PROVIDER_AUTHOR_AUTHORS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="DATE_OF_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="NEWS_BODY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "newsname",
            "providerauthorauthors",
            "dateofissue",
            "newsbody"
        })
        public static class SUBCATEGORY {

            @XmlElement(name = "NEWS_NAME", required = true)
            protected String newsname;
            @XmlElement(name = "PROVIDER_AUTHOR_AUTHORS", required = true)
            protected String providerauthorauthors;
            @XmlElement(name = "DATE_OF_ISSUE", required = true)
            protected String dateofissue;
            @XmlElement(name = "NEWS_BODY", required = true)
            protected String newsbody;
            @XmlAttribute(name = "Name", required = true)
            protected String name;

            /**
             * Gets the value of the newsname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNEWSNAME() {
                return newsname;
            }

            /**
             * Sets the value of the newsname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNEWSNAME(String value) {
                this.newsname = value;
            }

            /**
             * Gets the value of the providerauthorauthors property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPROVIDERAUTHORAUTHORS() {
                return providerauthorauthors;
            }

            /**
             * Sets the value of the providerauthorauthors property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPROVIDERAUTHORAUTHORS(String value) {
                this.providerauthorauthors = value;
            }

            /**
             * Gets the value of the dateofissue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDATEOFISSUE() {
                return dateofissue;
            }

            /**
             * Sets the value of the dateofissue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDATEOFISSUE(String value) {
                this.dateofissue = value;
            }

            /**
             * Gets the value of the newsbody property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNEWSBODY() {
                return newsbody;
            }

            /**
             * Sets the value of the newsbody property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNEWSBODY(String value) {
                this.newsbody = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            @Override
            public boolean equals(Object obj) {
                return super.equals(obj);
            }

            @Override
            public int hashCode() {
                return super.hashCode();
            }

            @Override
            public String toString() {
                return super.toString();
            }
        }

    }

}
