//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.09.17 at 10:44:21 PM MSK 
//


package by.htp.verishko.task1.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;


/**
 * <p>Java class for News complex type.
 * <p>
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="News"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="provider" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dateOfIssue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="newsBody" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "News")
public class News implements IBaseEntity {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "provider")
    protected String provider;
    @XmlAttribute(name = "dateOfIssue")
    protected String dateOfIssue;
    @XmlAttribute(name = "newsBody")
    protected String newsBody;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the provider property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the dateOfIssue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateOfIssue() {
        return dateOfIssue;
    }

    /**
     * Sets the value of the dateOfIssue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateOfIssue(String value) {
        this.dateOfIssue = value;
    }

    /**
     * Gets the value of the newsBody property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNewsBody() {
        return newsBody;
    }

    /**
     * Sets the value of the newsBody property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNewsBody(String value) {
        this.newsBody = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        News news = (News) o;
        return Objects.equals(name, news.name) &&
                Objects.equals(provider, news.provider) &&
                Objects.equals(dateOfIssue, news.dateOfIssue) &&
                Objects.equals(newsBody, news.newsBody);
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = result * 31 + (newsBody == null ? 0 : newsBody.hashCode()) * result;
        result = result * 31 + (name == null ? 0 : name.hashCode()) * result;
        result = result * 31 + (provider == null ? 0 : provider.hashCode()) * result;
        result = result * 31 + (dateOfIssue == null ? 0 : dateOfIssue.hashCode()) * result;
        return result;
    }

    @Override
    public String toString() {
        return "News{" +
                "name='" + name + '\'' +
                ", provider='" + provider + '\'' +
                ", date='" + dateOfIssue + '\'' +
                ", body='" + newsBody + '\'' +
                '}';
    }
}
