//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.08.30 at 01:59:18 AM MSK 
//


package by.htp.verishko.task1.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CATALOG }
     * 
     */
    public CATALOG createCATALOG() {
        return new CATALOG();
    }

    /**
     * Create an instance of {@link CATALOG.CATEGORY }
     * 
     */
    public CATALOG.CATEGORY createCATALOGCATEGORY() {
        return new CATALOG.CATEGORY();
    }

    /**
     * Create an instance of {@link CATALOG.CATEGORY.SUBCATEGORY }
     * 
     */
    public CATALOG.CATEGORY.SUBCATEGORY createCATALOGCATEGORYSUBCATEGORY() {
        return new CATALOG.CATEGORY.SUBCATEGORY();
    }

}
